/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LedgerEntryType = IDL.Variant({
  'Debit' : IDL.Null,
  'Credit' : IDL.Null,
});
export const ChallanItem = IDL.Record({
  'qty' : IDL.Int,
  'description' : IDL.Text,
});
export const BillLineItem = IDL.Record({
  'qty' : IDL.Int,
  'rate' : IDL.Float64,
  'description' : IDL.Text,
  'gstPercentage' : IDL.Float64,
});
export const JobStatus = IDL.Variant({
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const LedgerEntry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : LedgerEntryType,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const ProductionStage = IDL.Record({
  'completionDate' : IDL.Int,
  'assignedKarigar' : IDL.Text,
  'targetQuantity' : IDL.Int,
  'stageName' : IDL.Text,
});
export const Challan = IDL.Record({
  'id' : IDL.Nat,
  'challanNumber' : IDL.Text,
  'jobType' : IDL.Text,
  'date' : IDL.Int,
  'partyName' : IDL.Text,
  'items' : IDL.Vec(ChallanItem),
});
export const CompanyProfile = IDL.Record({
  'bankDetails' : IDL.Text,
  'gstNumber' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Design = IDL.Record({
  'id' : IDL.Nat,
  'fabricType' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'season' : IDL.Text,
  'number' : IDL.Text,
  'category' : IDL.Text,
});
export const Dispatch = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'trackingNumber' : IDL.Text,
  'date' : IDL.Int,
  'style' : IDL.Text,
  'quantity' : IDL.Int,
  'transportName' : IDL.Text,
  'buyerName' : IDL.Text,
});
export const FabricIssue = IDL.Record({
  'id' : IDL.Nat,
  'meters' : IDL.Float64,
  'fabricType' : IDL.Text,
  'date' : IDL.Int,
  'issuedTo' : IDL.Text,
});
export const FabricPurchase = IDL.Record({
  'id' : IDL.Nat,
  'meters' : IDL.Float64,
  'fabricType' : IDL.Text,
  'date' : IDL.Int,
  'color' : IDL.Text,
  'rate' : IDL.Float64,
  'invoiceNumber' : IDL.Text,
  'vendor' : IDL.Text,
  'amount' : IDL.Float64,
});
export const FabricStock = IDL.Record({
  'fabricType' : IDL.Text,
  'color' : IDL.Text,
  'availableMeters' : IDL.Float64,
  'issuedMeters' : IDL.Float64,
  'totalMeters' : IDL.Float64,
});
export const GSTBill = IDL.Record({
  'id' : IDL.Nat,
  'lineItems' : IDL.Vec(BillLineItem),
  'total' : IDL.Float64,
  'date' : IDL.Int,
  'billNumber' : IDL.Text,
  'buyerGST' : IDL.Text,
  'buyerName' : IDL.Text,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'date' : IDL.Int,
  'rate' : IDL.Float64,
  'karigarName' : IDL.Text,
  'style' : IDL.Text,
  'quantity' : IDL.Int,
  'partyName' : IDL.Text,
  'amount' : IDL.Float64,
  'jobNumber' : IDL.Text,
  'fabricLot' : IDL.Text,
});
export const KarigarLedgerEntry = IDL.Record({
  'id' : IDL.Nat,
  'balance' : IDL.Float64,
  'entries' : IDL.Vec(LedgerEntry),
  'karigarName' : IDL.Text,
});
export const Photo = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'category' : IDL.Text,
  'photoLabel' : IDL.Text,
});
export const ProductionPlan = IDL.Record({
  'id' : IDL.Nat,
  'stages' : IDL.Vec(ProductionStage),
  'deliveryDate' : IDL.Int,
  'styleName' : IDL.Text,
  'totalQuantity' : IDL.Int,
});
export const QualityCheck = IDL.Record({
  'id' : IDL.Nat,
  'jobType' : IDL.Text,
  'date' : IDL.Int,
  'passCount' : IDL.Int,
  'jobReference' : IDL.Text,
  'failCount' : IDL.Int,
  'remarks' : IDL.Text,
  'inspector' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAccountLedgerEntry' : IDL.Func(
      [LedgerEntryType, IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'addChallan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ChallanItem), IDL.Int],
      [IDL.Nat],
      [],
    ),
  'addDesign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addDispatch' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'addFabricPurchase' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'addGSTBill' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Vec(BillLineItem),
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'addJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        JobStatus,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'addKarigarLedgerEntry' : IDL.Func(
      [IDL.Text, IDL.Vec(LedgerEntry), IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
  'addProductionPlan' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int, IDL.Vec(ProductionStage)],
      [IDL.Nat],
      [],
    ),
  'addQualityCheck' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'getAccountLedgerEntry' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(LedgerEntry)],
      ['query'],
    ),
  'getChallan' : IDL.Func([IDL.Nat], [IDL.Opt(Challan)], ['query']),
  'getCompanyProfile' : IDL.Func([], [IDL.Opt(CompanyProfile)], ['query']),
  'getDesign' : IDL.Func([IDL.Nat], [IDL.Opt(Design)], ['query']),
  'getDispatch' : IDL.Func([IDL.Nat], [IDL.Opt(Dispatch)], ['query']),
  'getFabricIssue' : IDL.Func([IDL.Nat], [IDL.Opt(FabricIssue)], ['query']),
  'getFabricPurchase' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(FabricPurchase)],
      ['query'],
    ),
  'getFabricStock' : IDL.Func([IDL.Text], [IDL.Opt(FabricStock)], ['query']),
  'getGSTBill' : IDL.Func([IDL.Nat], [IDL.Opt(GSTBill)], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getKarigarLedger' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(KarigarLedgerEntry)],
      ['query'],
    ),
  'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(Photo)], ['query']),
  'getProductionPlan' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProductionPlan)],
      ['query'],
    ),
  'getQualityCheck' : IDL.Func([IDL.Nat], [IDL.Opt(QualityCheck)], ['query']),
  'issueFabric' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'listAccountLedgerEntries' : IDL.Func([], [IDL.Vec(LedgerEntry)], ['query']),
  'listChallans' : IDL.Func([], [IDL.Vec(Challan)], ['query']),
  'listDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'listDispatches' : IDL.Func([], [IDL.Vec(Dispatch)], ['query']),
  'listFabricIssues' : IDL.Func([], [IDL.Vec(FabricIssue)], ['query']),
  'listFabricPurchases' : IDL.Func([], [IDL.Vec(FabricPurchase)], ['query']),
  'listFabricStocks' : IDL.Func([], [IDL.Vec(FabricStock)], ['query']),
  'listGSTBills' : IDL.Func([], [IDL.Vec(GSTBill)], ['query']),
  'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'listKarigarLedgers' : IDL.Func([], [IDL.Vec(KarigarLedgerEntry)], ['query']),
  'listPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'listProductionPlans' : IDL.Func([], [IDL.Vec(ProductionPlan)], ['query']),
  'listQualityChecks' : IDL.Func([], [IDL.Vec(QualityCheck)], ['query']),
  'updateCompanyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LedgerEntryType = IDL.Variant({
    'Debit' : IDL.Null,
    'Credit' : IDL.Null,
  });
  const ChallanItem = IDL.Record({ 'qty' : IDL.Int, 'description' : IDL.Text });
  const BillLineItem = IDL.Record({
    'qty' : IDL.Int,
    'rate' : IDL.Float64,
    'description' : IDL.Text,
    'gstPercentage' : IDL.Float64,
  });
  const JobStatus = IDL.Variant({
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const LedgerEntry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : LedgerEntryType,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const ProductionStage = IDL.Record({
    'completionDate' : IDL.Int,
    'assignedKarigar' : IDL.Text,
    'targetQuantity' : IDL.Int,
    'stageName' : IDL.Text,
  });
  const Challan = IDL.Record({
    'id' : IDL.Nat,
    'challanNumber' : IDL.Text,
    'jobType' : IDL.Text,
    'date' : IDL.Int,
    'partyName' : IDL.Text,
    'items' : IDL.Vec(ChallanItem),
  });
  const CompanyProfile = IDL.Record({
    'bankDetails' : IDL.Text,
    'gstNumber' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Design = IDL.Record({
    'id' : IDL.Nat,
    'fabricType' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'season' : IDL.Text,
    'number' : IDL.Text,
    'category' : IDL.Text,
  });
  const Dispatch = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'trackingNumber' : IDL.Text,
    'date' : IDL.Int,
    'style' : IDL.Text,
    'quantity' : IDL.Int,
    'transportName' : IDL.Text,
    'buyerName' : IDL.Text,
  });
  const FabricIssue = IDL.Record({
    'id' : IDL.Nat,
    'meters' : IDL.Float64,
    'fabricType' : IDL.Text,
    'date' : IDL.Int,
    'issuedTo' : IDL.Text,
  });
  const FabricPurchase = IDL.Record({
    'id' : IDL.Nat,
    'meters' : IDL.Float64,
    'fabricType' : IDL.Text,
    'date' : IDL.Int,
    'color' : IDL.Text,
    'rate' : IDL.Float64,
    'invoiceNumber' : IDL.Text,
    'vendor' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const FabricStock = IDL.Record({
    'fabricType' : IDL.Text,
    'color' : IDL.Text,
    'availableMeters' : IDL.Float64,
    'issuedMeters' : IDL.Float64,
    'totalMeters' : IDL.Float64,
  });
  const GSTBill = IDL.Record({
    'id' : IDL.Nat,
    'lineItems' : IDL.Vec(BillLineItem),
    'total' : IDL.Float64,
    'date' : IDL.Int,
    'billNumber' : IDL.Text,
    'buyerGST' : IDL.Text,
    'buyerName' : IDL.Text,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'date' : IDL.Int,
    'rate' : IDL.Float64,
    'karigarName' : IDL.Text,
    'style' : IDL.Text,
    'quantity' : IDL.Int,
    'partyName' : IDL.Text,
    'amount' : IDL.Float64,
    'jobNumber' : IDL.Text,
    'fabricLot' : IDL.Text,
  });
  const KarigarLedgerEntry = IDL.Record({
    'id' : IDL.Nat,
    'balance' : IDL.Float64,
    'entries' : IDL.Vec(LedgerEntry),
    'karigarName' : IDL.Text,
  });
  const Photo = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'category' : IDL.Text,
    'photoLabel' : IDL.Text,
  });
  const ProductionPlan = IDL.Record({
    'id' : IDL.Nat,
    'stages' : IDL.Vec(ProductionStage),
    'deliveryDate' : IDL.Int,
    'styleName' : IDL.Text,
    'totalQuantity' : IDL.Int,
  });
  const QualityCheck = IDL.Record({
    'id' : IDL.Nat,
    'jobType' : IDL.Text,
    'date' : IDL.Int,
    'passCount' : IDL.Int,
    'jobReference' : IDL.Text,
    'failCount' : IDL.Int,
    'remarks' : IDL.Text,
    'inspector' : IDL.Text,
  });
  
  return IDL.Service({
    'addAccountLedgerEntry' : IDL.Func(
        [LedgerEntryType, IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'addChallan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ChallanItem), IDL.Int],
        [IDL.Nat],
        [],
      ),
    'addDesign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addDispatch' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'addFabricPurchase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'addGSTBill' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Vec(BillLineItem),
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'addJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          JobStatus,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'addKarigarLedgerEntry' : IDL.Func(
        [IDL.Text, IDL.Vec(LedgerEntry), IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
    'addProductionPlan' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int, IDL.Vec(ProductionStage)],
        [IDL.Nat],
        [],
      ),
    'addQualityCheck' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'getAccountLedgerEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(LedgerEntry)],
        ['query'],
      ),
    'getChallan' : IDL.Func([IDL.Nat], [IDL.Opt(Challan)], ['query']),
    'getCompanyProfile' : IDL.Func([], [IDL.Opt(CompanyProfile)], ['query']),
    'getDesign' : IDL.Func([IDL.Nat], [IDL.Opt(Design)], ['query']),
    'getDispatch' : IDL.Func([IDL.Nat], [IDL.Opt(Dispatch)], ['query']),
    'getFabricIssue' : IDL.Func([IDL.Nat], [IDL.Opt(FabricIssue)], ['query']),
    'getFabricPurchase' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(FabricPurchase)],
        ['query'],
      ),
    'getFabricStock' : IDL.Func([IDL.Text], [IDL.Opt(FabricStock)], ['query']),
    'getGSTBill' : IDL.Func([IDL.Nat], [IDL.Opt(GSTBill)], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getKarigarLedger' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(KarigarLedgerEntry)],
        ['query'],
      ),
    'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(Photo)], ['query']),
    'getProductionPlan' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProductionPlan)],
        ['query'],
      ),
    'getQualityCheck' : IDL.Func([IDL.Nat], [IDL.Opt(QualityCheck)], ['query']),
    'issueFabric' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'listAccountLedgerEntries' : IDL.Func(
        [],
        [IDL.Vec(LedgerEntry)],
        ['query'],
      ),
    'listChallans' : IDL.Func([], [IDL.Vec(Challan)], ['query']),
    'listDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'listDispatches' : IDL.Func([], [IDL.Vec(Dispatch)], ['query']),
    'listFabricIssues' : IDL.Func([], [IDL.Vec(FabricIssue)], ['query']),
    'listFabricPurchases' : IDL.Func([], [IDL.Vec(FabricPurchase)], ['query']),
    'listFabricStocks' : IDL.Func([], [IDL.Vec(FabricStock)], ['query']),
    'listGSTBills' : IDL.Func([], [IDL.Vec(GSTBill)], ['query']),
    'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'listKarigarLedgers' : IDL.Func(
        [],
        [IDL.Vec(KarigarLedgerEntry)],
        ['query'],
      ),
    'listPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'listProductionPlans' : IDL.Func([], [IDL.Vec(ProductionPlan)], ['query']),
    'listQualityChecks' : IDL.Func([], [IDL.Vec(QualityCheck)], ['query']),
    'updateCompanyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };