/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillLineItem {
  'qty' : bigint,
  'rate' : number,
  'description' : string,
  'gstPercentage' : number,
}
export interface Challan {
  'id' : bigint,
  'challanNumber' : string,
  'jobType' : string,
  'date' : bigint,
  'partyName' : string,
  'items' : Array<ChallanItem>,
}
export interface ChallanItem { 'qty' : bigint, 'description' : string }
export interface CompanyProfile {
  'bankDetails' : string,
  'gstNumber' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Design {
  'id' : bigint,
  'fabricType' : string,
  'name' : string,
  'description' : string,
  'season' : string,
  'number' : string,
  'category' : string,
}
export interface Dispatch {
  'id' : bigint,
  'status' : string,
  'trackingNumber' : string,
  'date' : bigint,
  'style' : string,
  'quantity' : bigint,
  'transportName' : string,
  'buyerName' : string,
}
export interface FabricIssue {
  'id' : bigint,
  'meters' : number,
  'fabricType' : string,
  'date' : bigint,
  'issuedTo' : string,
}
export interface FabricPurchase {
  'id' : bigint,
  'meters' : number,
  'fabricType' : string,
  'date' : bigint,
  'color' : string,
  'rate' : number,
  'invoiceNumber' : string,
  'vendor' : string,
  'amount' : number,
}
export interface FabricStock {
  'fabricType' : string,
  'color' : string,
  'availableMeters' : number,
  'issuedMeters' : number,
  'totalMeters' : number,
}
export interface GSTBill {
  'id' : bigint,
  'lineItems' : Array<BillLineItem>,
  'total' : number,
  'date' : bigint,
  'billNumber' : string,
  'buyerGST' : string,
  'buyerName' : string,
}
export interface Job {
  'id' : bigint,
  'status' : JobStatus,
  'date' : bigint,
  'rate' : number,
  'karigarName' : string,
  'style' : string,
  'quantity' : bigint,
  'partyName' : string,
  'amount' : number,
  'jobNumber' : string,
  'fabricLot' : string,
}
export type JobStatus = { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface KarigarLedgerEntry {
  'id' : bigint,
  'balance' : number,
  'entries' : Array<LedgerEntry>,
  'karigarName' : string,
}
export interface LedgerEntry {
  'id' : bigint,
  'entryType' : LedgerEntryType,
  'date' : bigint,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export type LedgerEntryType = { 'Debit' : null } |
  { 'Credit' : null };
export interface Photo {
  'id' : bigint,
  'date' : bigint,
  'category' : string,
  'photoLabel' : string,
}
export interface ProductionPlan {
  'id' : bigint,
  'stages' : Array<ProductionStage>,
  'deliveryDate' : bigint,
  'styleName' : string,
  'totalQuantity' : bigint,
}
export interface ProductionStage {
  'completionDate' : bigint,
  'assignedKarigar' : string,
  'targetQuantity' : bigint,
  'stageName' : string,
}
export interface QualityCheck {
  'id' : bigint,
  'jobType' : string,
  'date' : bigint,
  'passCount' : bigint,
  'jobReference' : string,
  'failCount' : bigint,
  'remarks' : string,
  'inspector' : string,
}
export interface _SERVICE {
  'addAccountLedgerEntry' : ActorMethod<
    [LedgerEntryType, string, number, string, bigint],
    bigint
  >,
  'addChallan' : ActorMethod<
    [string, string, string, Array<ChallanItem>, bigint],
    bigint
  >,
  'addDesign' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addDispatch' : ActorMethod<
    [string, string, bigint, string, string, string, bigint],
    bigint
  >,
  'addFabricPurchase' : ActorMethod<
    [string, string, string, number, number, number, string, bigint],
    bigint
  >,
  'addGSTBill' : ActorMethod<
    [string, string, string, bigint, Array<BillLineItem>, number],
    bigint
  >,
  'addJob' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      number,
      number,
      string,
      JobStatus,
      bigint,
    ],
    bigint
  >,
  'addKarigarLedgerEntry' : ActorMethod<
    [string, Array<LedgerEntry>, number],
    bigint
  >,
  'addPhoto' : ActorMethod<[string, string, bigint], bigint>,
  'addProductionPlan' : ActorMethod<
    [string, bigint, bigint, Array<ProductionStage>],
    bigint
  >,
  'addQualityCheck' : ActorMethod<
    [string, string, string, bigint, bigint, string, bigint],
    bigint
  >,
  'getAccountLedgerEntry' : ActorMethod<[bigint], [] | [LedgerEntry]>,
  'getChallan' : ActorMethod<[bigint], [] | [Challan]>,
  'getCompanyProfile' : ActorMethod<[], [] | [CompanyProfile]>,
  'getDesign' : ActorMethod<[bigint], [] | [Design]>,
  'getDispatch' : ActorMethod<[bigint], [] | [Dispatch]>,
  'getFabricIssue' : ActorMethod<[bigint], [] | [FabricIssue]>,
  'getFabricPurchase' : ActorMethod<[bigint], [] | [FabricPurchase]>,
  'getFabricStock' : ActorMethod<[string], [] | [FabricStock]>,
  'getGSTBill' : ActorMethod<[bigint], [] | [GSTBill]>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getKarigarLedger' : ActorMethod<[bigint], [] | [KarigarLedgerEntry]>,
  'getPhoto' : ActorMethod<[bigint], [] | [Photo]>,
  'getProductionPlan' : ActorMethod<[bigint], [] | [ProductionPlan]>,
  'getQualityCheck' : ActorMethod<[bigint], [] | [QualityCheck]>,
  'issueFabric' : ActorMethod<[string, number, string, bigint], bigint>,
  'listAccountLedgerEntries' : ActorMethod<[], Array<LedgerEntry>>,
  'listChallans' : ActorMethod<[], Array<Challan>>,
  'listDesigns' : ActorMethod<[], Array<Design>>,
  'listDispatches' : ActorMethod<[], Array<Dispatch>>,
  'listFabricIssues' : ActorMethod<[], Array<FabricIssue>>,
  'listFabricPurchases' : ActorMethod<[], Array<FabricPurchase>>,
  'listFabricStocks' : ActorMethod<[], Array<FabricStock>>,
  'listGSTBills' : ActorMethod<[], Array<GSTBill>>,
  'listJobs' : ActorMethod<[], Array<Job>>,
  'listKarigarLedgers' : ActorMethod<[], Array<KarigarLedgerEntry>>,
  'listPhotos' : ActorMethod<[], Array<Photo>>,
  'listProductionPlans' : ActorMethod<[], Array<ProductionPlan>>,
  'listQualityChecks' : ActorMethod<[], Array<QualityCheck>>,
  'updateCompanyProfile' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];