/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Photo {
    id: bigint;
    date: bigint;
    category: string;
    photoLabel: string;
}
export interface CompanyProfile {
    bankDetails: string;
    gstNumber: string;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface ProductionPlan {
    id: bigint;
    stages: Array<ProductionStage>;
    deliveryDate: bigint;
    styleName: string;
    totalQuantity: bigint;
}
export interface FabricIssue {
    id: bigint;
    meters: number;
    fabricType: string;
    date: bigint;
    issuedTo: string;
}
export interface LedgerEntry {
    id: bigint;
    entryType: LedgerEntryType;
    date: bigint;
    description: string;
    category: string;
    amount: number;
}
export interface FabricPurchase {
    id: bigint;
    meters: number;
    fabricType: string;
    date: bigint;
    color: string;
    rate: number;
    invoiceNumber: string;
    vendor: string;
    amount: number;
}
export interface Design {
    id: bigint;
    fabricType: string;
    name: string;
    description: string;
    season: string;
    number: string;
    category: string;
}
export interface QualityCheck {
    id: bigint;
    jobType: string;
    date: bigint;
    passCount: bigint;
    jobReference: string;
    failCount: bigint;
    remarks: string;
    inspector: string;
}
export interface KarigarLedgerEntry {
    id: bigint;
    balance: number;
    entries: Array<LedgerEntry>;
    karigarName: string;
}
export interface ProductionStage {
    completionDate: bigint;
    assignedKarigar: string;
    targetQuantity: bigint;
    stageName: string;
}
export interface Job {
    id: bigint;
    status: JobStatus;
    date: bigint;
    rate: number;
    karigarName: string;
    style: string;
    quantity: bigint;
    partyName: string;
    amount: number;
    jobNumber: string;
    fabricLot: string;
}
export interface GSTBill {
    id: bigint;
    lineItems: Array<BillLineItem>;
    total: number;
    date: bigint;
    billNumber: string;
    buyerGST: string;
    buyerName: string;
}
export interface Challan {
    id: bigint;
    challanNumber: string;
    jobType: string;
    date: bigint;
    partyName: string;
    items: Array<ChallanItem>;
}
export interface BillLineItem {
    qty: bigint;
    rate: number;
    description: string;
    gstPercentage: number;
}
export interface FabricStock {
    fabricType: string;
    color: string;
    availableMeters: number;
    issuedMeters: number;
    totalMeters: number;
}
export interface Dispatch {
    id: bigint;
    status: string;
    trackingNumber: string;
    date: bigint;
    style: string;
    quantity: bigint;
    transportName: string;
    buyerName: string;
}
export interface ChallanItem {
    qty: bigint;
    description: string;
}
export enum JobStatus {
    InProgress = "InProgress",
    Completed = "Completed",
    Pending = "Pending"
}
export enum LedgerEntryType {
    Debit = "Debit",
    Credit = "Credit"
}
export interface backendInterface {
    addAccountLedgerEntry(entryType: LedgerEntryType, category: string, amount: number, description: string, date: bigint): Promise<bigint>;
    addChallan(challanNumber: string, jobType: string, partyName: string, items: Array<ChallanItem>, date: bigint): Promise<bigint>;
    addDesign(number: string, name: string, category: string, season: string, fabricType: string, description: string): Promise<bigint>;
    addDispatch(style: string, buyerName: string, quantity: bigint, transportName: string, trackingNumber: string, status: string, date: bigint): Promise<bigint>;
    addFabricPurchase(vendor: string, fabricType: string, color: string, meters: number, rate: number, amount: number, invoiceNumber: string, date: bigint): Promise<bigint>;
    addGSTBill(billNumber: string, buyerName: string, buyerGST: string, date: bigint, lineItems: Array<BillLineItem>, total: number): Promise<bigint>;
    addJob(jobNumber: string, style: string, partyName: string, fabricLot: string, quantity: bigint, rate: number, amount: number, karigarName: string, status: JobStatus, date: bigint): Promise<bigint>;
    addKarigarLedgerEntry(karigarName: string, entries: Array<LedgerEntry>, balance: number): Promise<bigint>;
    addPhoto(photoLabel: string, category: string, date: bigint): Promise<bigint>;
    addProductionPlan(styleName: string, totalQuantity: bigint, deliveryDate: bigint, stages: Array<ProductionStage>): Promise<bigint>;
    addQualityCheck(jobReference: string, jobType: string, inspector: string, passCount: bigint, failCount: bigint, remarks: string, date: bigint): Promise<bigint>;
    getAccountLedgerEntry(id: bigint): Promise<LedgerEntry | null>;
    getChallan(id: bigint): Promise<Challan | null>;
    getCompanyProfile(): Promise<CompanyProfile | null>;
    getDesign(id: bigint): Promise<Design | null>;
    getDispatch(id: bigint): Promise<Dispatch | null>;
    getFabricIssue(id: bigint): Promise<FabricIssue | null>;
    getFabricPurchase(id: bigint): Promise<FabricPurchase | null>;
    getFabricStock(fabricType: string): Promise<FabricStock | null>;
    getGSTBill(id: bigint): Promise<GSTBill | null>;
    getJob(id: bigint): Promise<Job | null>;
    getKarigarLedger(id: bigint): Promise<KarigarLedgerEntry | null>;
    getPhoto(id: bigint): Promise<Photo | null>;
    getProductionPlan(id: bigint): Promise<ProductionPlan | null>;
    getQualityCheck(id: bigint): Promise<QualityCheck | null>;
    issueFabric(fabricType: string, meters: number, issuedTo: string, date: bigint): Promise<bigint>;
    listAccountLedgerEntries(): Promise<Array<LedgerEntry>>;
    listChallans(): Promise<Array<Challan>>;
    listDesigns(): Promise<Array<Design>>;
    listDispatches(): Promise<Array<Dispatch>>;
    listFabricIssues(): Promise<Array<FabricIssue>>;
    listFabricPurchases(): Promise<Array<FabricPurchase>>;
    listFabricStocks(): Promise<Array<FabricStock>>;
    listGSTBills(): Promise<Array<GSTBill>>;
    listJobs(): Promise<Array<Job>>;
    listKarigarLedgers(): Promise<Array<KarigarLedgerEntry>>;
    listPhotos(): Promise<Array<Photo>>;
    listProductionPlans(): Promise<Array<ProductionPlan>>;
    listQualityChecks(): Promise<Array<QualityCheck>>;
    updateCompanyProfile(name: string, address: string, gstNumber: string, phone: string, email: string, bankDetails: string): Promise<void>;
}
import type { Challan as _Challan, CompanyProfile as _CompanyProfile, Design as _Design, Dispatch as _Dispatch, FabricIssue as _FabricIssue, FabricPurchase as _FabricPurchase, FabricStock as _FabricStock, GSTBill as _GSTBill, Job as _Job, JobStatus as _JobStatus, KarigarLedgerEntry as _KarigarLedgerEntry, LedgerEntry as _LedgerEntry, LedgerEntryType as _LedgerEntryType, Photo as _Photo, ProductionPlan as _ProductionPlan, QualityCheck as _QualityCheck } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAccountLedgerEntry(arg0: LedgerEntryType, arg1: string, arg2: number, arg3: string, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAccountLedgerEntry(to_candid_LedgerEntryType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAccountLedgerEntry(to_candid_LedgerEntryType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addChallan(arg0: string, arg1: string, arg2: string, arg3: Array<ChallanItem>, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChallan(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChallan(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addDesign(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDesign(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDesign(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addDispatch(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDispatch(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDispatch(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addFabricPurchase(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: string, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addFabricPurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFabricPurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addGSTBill(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Array<BillLineItem>, arg5: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGSTBill(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGSTBill(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addJob(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: number, arg6: number, arg7: string, arg8: JobStatus, arg9: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_JobStatus_n3(this._uploadFile, this._downloadFile, arg8), arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_JobStatus_n3(this._uploadFile, this._downloadFile, arg8), arg9);
            return result;
        }
    }
    async addKarigarLedgerEntry(arg0: string, arg1: Array<LedgerEntry>, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addKarigarLedgerEntry(arg0, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKarigarLedgerEntry(arg0, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addPhoto(arg0: string, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhoto(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhoto(arg0, arg1, arg2);
            return result;
        }
    }
    async addProductionPlan(arg0: string, arg1: bigint, arg2: bigint, arg3: Array<ProductionStage>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductionPlan(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductionPlan(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addQualityCheck(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQualityCheck(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQualityCheck(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getAccountLedgerEntry(arg0: bigint): Promise<LedgerEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountLedgerEntry(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountLedgerEntry(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallan(arg0: bigint): Promise<Challan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallan(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallan(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyProfile(): Promise<CompanyProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesign(arg0: bigint): Promise<Design | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesign(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesign(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDispatch(arg0: bigint): Promise<Dispatch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDispatch(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDispatch(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFabricIssue(arg0: bigint): Promise<FabricIssue | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFabricIssue(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFabricIssue(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFabricPurchase(arg0: bigint): Promise<FabricPurchase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFabricPurchase(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFabricPurchase(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFabricStock(arg0: string): Promise<FabricStock | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFabricStock(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFabricStock(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGSTBill(arg0: bigint): Promise<GSTBill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGSTBill(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGSTBill(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: bigint): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKarigarLedger(arg0: bigint): Promise<KarigarLedgerEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKarigarLedger(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKarigarLedger(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhoto(arg0: bigint): Promise<Photo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhoto(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhoto(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductionPlan(arg0: bigint): Promise<ProductionPlan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionPlan(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionPlan(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQualityCheck(arg0: bigint): Promise<QualityCheck | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQualityCheck(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQualityCheck(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async issueFabric(arg0: string, arg1: number, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.issueFabric(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.issueFabric(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async listAccountLedgerEntries(): Promise<Array<LedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAccountLedgerEntries();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAccountLedgerEntries();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listChallans(): Promise<Array<Challan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChallans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChallans();
            return result;
        }
    }
    async listDesigns(): Promise<Array<Design>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDesigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDesigns();
            return result;
        }
    }
    async listDispatches(): Promise<Array<Dispatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDispatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDispatches();
            return result;
        }
    }
    async listFabricIssues(): Promise<Array<FabricIssue>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFabricIssues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFabricIssues();
            return result;
        }
    }
    async listFabricPurchases(): Promise<Array<FabricPurchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFabricPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFabricPurchases();
            return result;
        }
    }
    async listFabricStocks(): Promise<Array<FabricStock>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFabricStocks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFabricStocks();
            return result;
        }
    }
    async listGSTBills(): Promise<Array<GSTBill>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGSTBills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGSTBills();
            return result;
        }
    }
    async listJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listKarigarLedgers(): Promise<Array<KarigarLedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKarigarLedgers();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKarigarLedgers();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPhotos(): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPhotos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPhotos();
            return result;
        }
    }
    async listProductionPlans(): Promise<Array<ProductionPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductionPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductionPlans();
            return result;
        }
    }
    async listQualityChecks(): Promise<Array<QualityCheck>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQualityChecks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQualityChecks();
            return result;
        }
    }
    async updateCompanyProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanyProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanyProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_JobStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_KarigarLedgerEntry_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KarigarLedgerEntry): KarigarLedgerEntry {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_LedgerEntryType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LedgerEntryType): LedgerEntryType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_LedgerEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LedgerEntry): LedgerEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Challan]): Challan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanyProfile]): CompanyProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Design]): Design | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Dispatch]): Dispatch | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FabricIssue]): FabricIssue | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FabricPurchase]): FabricPurchase | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FabricStock]): FabricStock | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GSTBill]): GSTBill | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KarigarLedgerEntry]): KarigarLedgerEntry | null {
    return value.length === 0 ? null : from_candid_KarigarLedgerEntry_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Photo]): Photo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductionPlan]): ProductionPlan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QualityCheck]): QualityCheck | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LedgerEntry]): LedgerEntry | null {
    return value.length === 0 ? null : from_candid_LedgerEntry_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    entryType: _LedgerEntryType;
    date: bigint;
    description: string;
    category: string;
    amount: number;
}): {
    id: bigint;
    entryType: LedgerEntryType;
    date: bigint;
    description: string;
    category: string;
    amount: number;
} {
    return {
        id: value.id,
        entryType: from_candid_LedgerEntryType_n11(_uploadFile, _downloadFile, value.entryType),
        date: value.date,
        description: value.description,
        category: value.category,
        amount: value.amount
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _JobStatus;
    date: bigint;
    rate: number;
    karigarName: string;
    style: string;
    quantity: bigint;
    partyName: string;
    amount: number;
    jobNumber: string;
    fabricLot: string;
}): {
    id: bigint;
    status: JobStatus;
    date: bigint;
    rate: number;
    karigarName: string;
    style: string;
    quantity: bigint;
    partyName: string;
    amount: number;
    jobNumber: string;
    fabricLot: string;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n24(_uploadFile, _downloadFile, value.status),
        date: value.date,
        rate: value.rate,
        karigarName: value.karigarName,
        style: value.style,
        quantity: value.quantity,
        partyName: value.partyName,
        amount: value.amount,
        jobNumber: value.jobNumber,
        fabricLot: value.fabricLot
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    balance: number;
    entries: Array<_LedgerEntry>;
    karigarName: string;
}): {
    id: bigint;
    balance: number;
    entries: Array<LedgerEntry>;
    karigarName: string;
} {
    return {
        id: value.id,
        balance: value.balance,
        entries: from_candid_vec_n29(_uploadFile, _downloadFile, value.entries),
        karigarName: value.karigarName
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Debit: null;
} | {
    Credit: null;
}): LedgerEntryType {
    return "Debit" in value ? LedgerEntryType.Debit : "Credit" in value ? LedgerEntryType.Credit : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InProgress: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): JobStatus {
    return "InProgress" in value ? JobStatus.InProgress : "Completed" in value ? JobStatus.Completed : "Pending" in value ? JobStatus.Pending : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LedgerEntry>): Array<LedgerEntry> {
    return value.map((x)=>from_candid_LedgerEntry_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KarigarLedgerEntry>): Array<KarigarLedgerEntry> {
    return value.map((x)=>from_candid_KarigarLedgerEntry_n27(_uploadFile, _downloadFile, x));
}
function to_candid_JobStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LedgerEntryType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LedgerEntryType): _LedgerEntryType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_LedgerEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LedgerEntry): _LedgerEntry {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    entryType: LedgerEntryType;
    date: bigint;
    description: string;
    category: string;
    amount: number;
}): {
    id: bigint;
    entryType: _LedgerEntryType;
    date: bigint;
    description: string;
    category: string;
    amount: number;
} {
    return {
        id: value.id,
        entryType: to_candid_LedgerEntryType_n1(_uploadFile, _downloadFile, value.entryType),
        date: value.date,
        description: value.description,
        category: value.category,
        amount: value.amount
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LedgerEntryType): {
    Debit: null;
} | {
    Credit: null;
} {
    return value == LedgerEntryType.Debit ? {
        Debit: null
    } : value == LedgerEntryType.Credit ? {
        Credit: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    InProgress: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == JobStatus.InProgress ? {
        InProgress: null
    } : value == JobStatus.Completed ? {
        Completed: null
    } : value == JobStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LedgerEntry>): Array<_LedgerEntry> {
    return value.map((x)=>to_candid_LedgerEntry_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
